include: package:flutter_lints/flutter.yaml

linter:
  - avoid_web_libraries_in_flutter
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore