name: money
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  path: any
  get_it: ^7.6.4
  fl_chart: ^0.63.0
  equatable: ^2.0.5
  animations: ^2.0.8
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.2.1
  month_picker_dialog: ^2.0.2
  flutter_multi_formatter: ^2.11.9
  bloc: ^8.1.2
  meta: any
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  lunar_calendar_converter_new: ^2.0.0
  dartz: ^0.10.1
  injectable: ^2.3.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_messaging: ^14.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.2
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0

flutter:

  uses-material-design: true
  assets:
    - assets/