name: money
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
#  sdk: ">=2.17.6 <3.0.0"
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  path: any
  http: ^0.13.6
  get_it: ^7.6.0
  sqflite: ^2.2.8+4
  fl_chart: ^0.62.0
  equatable: ^2.0.5
  animations: ^2.0.7
  flutter_bloc: ^8.1.2
  firebase_core: ^2.12.0
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.7.0
  json_annotation: ^4.8.1
  another_flushbar: ^1.12.30
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.1.1
  month_picker_dialog: ^2.0.0
  flutter_multi_formatter: ^2.11.0
  bloc: ^8.1.1
  meta: any
  freezed_annotation: ^2.2.0
  freezed: ^2.3.4
  google_fonts: ^4.0.4
  lunar_calendar_converter_new: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true
  assets:
    - assets/