name: money
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.5
  get_it: ^7.2.0
  analyzer: ^5.1.0
  fl_chart: ^0.55.2
  equatable: ^2.0.5
  animations: ^2.0.5
  flutter_bloc: ^8.1.1
  firebase_core: ^1.24.0
  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.5.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  month_picker_dialog_2: ^0.5.6
  flutter_multi_formatter: ^2.8.0

  bloc: ^8.1.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:

    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1

flutter:

  uses-material-design: true

  assets:
    - image/
