name: money
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  path: any
  http: ^0.13.5
  get_it: ^7.2.0
  sqflite: ^2.2.5
  fl_chart: ^0.61.0
  equatable: ^2.0.5
  animations: ^2.0.7
  flutter_bloc: ^8.1.2
  firebase_core: ^2.7.1
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.4.4
  json_annotation: ^4.8.0
  another_flushbar: ^1.12.29
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.18
  month_picker_dialog_2: ^0.6.2+1
  flutter_multi_formatter: ^2.10.2
  bloc: ^8.1.1
  meta: any
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

