name: money
description: Money Project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  path: ^1.9.0
  get_it: ^7.7.0
  fl_chart: ^0.68.0
  equatable: ^2.0.5
  animations: ^2.0.11
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  month_picker_dialog: ^4.0.1
  flutter_multi_formatter: ^2.13.0
  bloc: ^8.1.4
  freezed_annotation: ^2.4.4
  lunar_calendar_converter_new: ^2.0.0
  dartz: ^0.10.1
  injectable: ^2.4.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

flutter:

  uses-material-design: true
  assets:
    - assets/