name: money
description: Money Project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  path: ^1.9.0
  get_it: ^7.7.0
  fl_chart: ^0.67.0
  equatable: ^2.0.5
  animations: ^2.0.11
  flutter_bloc: ^8.1.5
  cupertino_icons: ^1.0.8
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.2.3
  month_picker_dialog: ^2.11.2
  flutter_multi_formatter: ^2.12.4
  bloc: ^8.1.4
  meta: ^1.11.0
  freezed_annotation: ^2.4.1
  lunar_calendar_converter_new: ^2.0.0
  dartz: ^0.10.1
  injectable: ^2.4.1
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.1

flutter:

  uses-material-design: true
  assets:
    - assets/