name: money
description: Money Project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  path: any
  get_it: ^7.6.7
  fl_chart: ^0.66.2
  equatable: ^2.0.5
  animations: ^2.0.11
  flutter_bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  month_picker_dialog: ^2.11.1
  flutter_multi_formatter: ^2.12.4
  bloc: ^8.1.3
  meta: any
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  lunar_calendar_converter_new: ^2.0.0
  dartz: ^0.10.1
  injectable: ^2.3.4
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.7
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.5.0

flutter:

  uses-material-design: true
  assets:
    - assets/