// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQDzXaixJnpoDMckuymokPmOOCzV9O-M',
    appId: '1:368046592663:web:79e21bece6472748838fd2',
    messagingSenderId: '368046592663',
    projectId: 'money-92165',
    authDomain: 'money-92165.firebaseapp.com',
    storageBucket: 'money-92165.appspot.com',
    measurementId: 'G-NLRPSYSNWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5MdBZxtMujtYVKwbTXCS-BABwiXcf8a4',
    appId: '1:368046592663:android:21f0a0d070572d42838fd2',
    messagingSenderId: '368046592663',
    projectId: 'money-92165',
    storageBucket: 'money-92165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_eKPPv74nuJFEs6_k29Ihwi_ohKZgOU',
    appId: '1:368046592663:ios:8b210fbd0d109759838fd2',
    messagingSenderId: '368046592663',
    projectId: 'money-92165',
    storageBucket: 'money-92165.appspot.com',
    iosClientId: '368046592663-tjhp09pgktoaq40rdrt4500qembksrcu.apps.googleusercontent.com',
    iosBundleId: 'vn.thanhpt.money',
  );
}
